apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: my-cluster
  labels:
    app: my-cluster
spec:
  kafka:
    replicas: 3
    resources:
      requests:
        memory: 2Gi
      limits:
        memory: 2Gi
    jvmOptions:
      -Xms: 1024m
      -Xmx: 1024m
      gcLoggingEnabled: false
    listeners:
      plain: {}
      tls:
        authentication:
          type: tls
      external:
        type: route
        authentication:
          type: tls
    authorization:
      type: simple
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: true
  zookeeper:
    replicas: 3
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 1Gi
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: true
    jvmOptions:
      gcLoggingEnabled: false
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 256Mi
        limits:
          memory: 256Mi
      jvmOptions:
        gcLoggingEnabled: false
    userOperator:
      resources:
        requests:
          memory: 256Mi
        limits:
          memory: 256Mi
      jvmOptions:
        gcLoggingEnabled: false